create table if not exists public.ai_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists ai_chat_messages_user_created_idx
  on public.ai_chat_messages(user_id, created_at desc);
create index if not exists ai_chat_messages_created_idx
  on public.ai_chat_messages(created_at desc);
create index if not exists ai_chat_messages_request_created_idx
  on public.ai_chat_messages(request_key, created_at desc);

alter table public.ai_chat_messages enable row level security;
revoke all on table public.ai_chat_messages from public, anon, authenticated;
grant select, insert, delete on table public.ai_chat_messages to service_role;
grant usage, select on sequence public.ai_chat_messages_id_seq to service_role;

create or replace function public.claim_ai_chat_message(
  p_user_id uuid,
  p_request_key text,
  p_user_hourly_limit integer,
  p_user_daily_limit integer,
  p_network_hourly_limit integer,
  p_network_daily_limit integer,
  p_global_daily_limit integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  user_hourly_count integer;
  user_daily_count integer;
  network_hourly_count integer;
  network_daily_count integer;
  global_daily_count integer;
begin
  if p_user_id is null
    or p_request_key is null
    or char_length(p_request_key) < 32
    or p_user_hourly_limit < 1
    or p_user_daily_limit < 1
    or p_network_hourly_limit < 1
    or p_network_daily_limit < 1
    or p_global_daily_limit < 1 then
    raise exception 'Invalid AI chat quota';
  end if;

  perform pg_advisory_xact_lock(hashtext('codart_ai_chat_quota'));
  delete from public.ai_chat_messages where created_at < now() - interval '7 days';

  select count(*) into user_hourly_count
  from public.ai_chat_messages
  where user_id = p_user_id and created_at >= now() - interval '1 hour';
  if user_hourly_count >= p_user_hourly_limit then
    return jsonb_build_object('allowed', false, 'reason', 'user_hourly');
  end if;

  select count(*) into user_daily_count
  from public.ai_chat_messages
  where user_id = p_user_id
    and created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc';
  if user_daily_count >= p_user_daily_limit then
    return jsonb_build_object('allowed', false, 'reason', 'user_daily');
  end if;

  select count(*) into network_hourly_count
  from public.ai_chat_messages
  where request_key = p_request_key and created_at >= now() - interval '1 hour';
  if network_hourly_count >= p_network_hourly_limit then
    return jsonb_build_object('allowed', false, 'reason', 'network_hourly');
  end if;

  select count(*) into network_daily_count
  from public.ai_chat_messages
  where request_key = p_request_key
    and created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc';
  if network_daily_count >= p_network_daily_limit then
    return jsonb_build_object('allowed', false, 'reason', 'network_daily');
  end if;

  select count(*) into global_daily_count
  from public.ai_chat_messages
  where created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc';
  if global_daily_count >= p_global_daily_limit then
    return jsonb_build_object('allowed', false, 'reason', 'global_daily');
  end if;

  insert into public.ai_chat_messages(user_id, request_key)
  values (p_user_id, p_request_key);

  return jsonb_build_object(
    'allowed', true,
    'userDailyRemaining', greatest(0, p_user_daily_limit - user_daily_count - 1),
    'globalDailyRemaining', greatest(0, p_global_daily_limit - global_daily_count - 1)
  );
end;
$$;

revoke all on function public.claim_ai_chat_message(uuid, text, integer, integer, integer, integer, integer)
  from public, anon, authenticated;
grant execute on function public.claim_ai_chat_message(uuid, text, integer, integer, integer, integer, integer)
  to service_role;
