create table if not exists public.ai_voice_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_key text not null,
  created_at timestamptz not null default now()
);

alter table public.ai_voice_sessions add column if not exists request_key text;
update public.ai_voice_sessions set request_key = 'legacy' where request_key is null;
alter table public.ai_voice_sessions alter column request_key set not null;

create index if not exists ai_voice_sessions_user_created_idx
  on public.ai_voice_sessions(user_id, created_at desc);
create index if not exists ai_voice_sessions_created_idx
  on public.ai_voice_sessions(created_at desc);
create index if not exists ai_voice_sessions_request_created_idx
  on public.ai_voice_sessions(request_key, created_at desc);

alter table public.ai_voice_sessions enable row level security;
revoke all on table public.ai_voice_sessions from public, anon, authenticated;
grant select, insert, delete on table public.ai_voice_sessions to service_role;
grant usage, select on sequence public.ai_voice_sessions_id_seq to service_role;

drop function if exists public.claim_ai_voice_session(uuid, integer, integer, integer);

create or replace function public.claim_ai_voice_session(
  p_user_id uuid,
  p_request_key text,
  p_user_hourly_limit integer,
  p_user_daily_limit integer,
  p_network_hourly_limit integer,
  p_network_daily_limit integer,
  p_global_daily_limit integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  user_hourly_count integer;
  user_daily_count integer;
  network_hourly_count integer;
  network_daily_count integer;
  global_daily_count integer;
begin
  if p_user_id is null
    or p_request_key is null
    or char_length(p_request_key) < 32
    or p_user_hourly_limit < 1
    or p_user_daily_limit < 1
    or p_network_hourly_limit < 1
    or p_network_daily_limit < 1
    or p_global_daily_limit < 1 then
    raise exception 'Invalid voice session quota';
  end if;

  perform pg_advisory_xact_lock(hashtext('codart_ai_voice_quota'));
  delete from public.ai_voice_sessions where created_at < now() - interval '7 days';

  select count(*) into user_hourly_count
  from public.ai_voice_sessions
  where user_id = p_user_id and created_at >= now() - interval '1 hour';
  if user_hourly_count >= p_user_hourly_limit then
    return jsonb_build_object('allowed', false, 'reason', 'user_hourly');
  end if;

  select count(*) into user_daily_count
  from public.ai_voice_sessions
  where user_id = p_user_id and created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc';
  if user_daily_count >= p_user_daily_limit then
    return jsonb_build_object('allowed', false, 'reason', 'user_daily');
  end if;

  select count(*) into network_hourly_count
  from public.ai_voice_sessions
  where request_key = p_request_key and created_at >= now() - interval '1 hour';
  if network_hourly_count >= p_network_hourly_limit then
    return jsonb_build_object('allowed', false, 'reason', 'network_hourly');
  end if;

  select count(*) into network_daily_count
  from public.ai_voice_sessions
  where request_key = p_request_key and created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc';
  if network_daily_count >= p_network_daily_limit then
    return jsonb_build_object('allowed', false, 'reason', 'network_daily');
  end if;

  select count(*) into global_daily_count
  from public.ai_voice_sessions
  where created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc';
  if global_daily_count >= p_global_daily_limit then
    return jsonb_build_object('allowed', false, 'reason', 'global_daily');
  end if;

  insert into public.ai_voice_sessions(user_id, request_key) values (p_user_id, p_request_key);
  return jsonb_build_object(
    'allowed', true,
    'userDailyRemaining', greatest(0, p_user_daily_limit - user_daily_count - 1),
    'globalDailyRemaining', greatest(0, p_global_daily_limit - global_daily_count - 1)
  );
end;
$$;

revoke all on function public.claim_ai_voice_session(uuid, text, integer, integer, integer, integer, integer) from public, anon, authenticated;
grant execute on function public.claim_ai_voice_session(uuid, text, integer, integer, integer, integer, integer) to service_role;
