-- Run this in the Supabase SQL editor once.
create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 120),
  description text not null check (char_length(description) between 1 and 600),
  image_url text not null,
  image_path text not null,
  price numeric(12, 2) not null check (price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null check (char_length(customer_name) between 1 and 120),
  customer_phone text not null check (char_length(customer_phone) between 3 and 40),
  customer_note text not null default '' check (char_length(customer_note) <= 1000),
  total numeric(12, 2) not null check (total >= 0),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'fulfilled', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders
  add column if not exists user_id uuid references auth.users(id) on delete set null;

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_title text not null,
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 99),
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  visitor_id uuid not null,
  product_id text not null,
  created_at timestamptz not null default now(),
  primary key (visitor_id, product_id)
);

create table if not exists public.cart_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  quantity integer not null check (quantity between 1 and 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.hero_slides (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 100),
  subtitle text not null default '' check (char_length(subtitle) <= 240),
  image_url text not null,
  image_path text not null,
  cta_label text not null default 'Shop now' check (char_length(cta_label) between 1 and 40),
  cta_href text not null default '/#products' check (char_length(cta_href) between 1 and 300),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_daily (
  day date not null default current_date,
  metric text not null check (metric in ('page_view', 'click')),
  event_key text not null check (char_length(event_key) between 1 and 180),
  event_count bigint not null default 0 check (event_count >= 0),
  primary key (day, metric, event_key)
);

create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_user_id_idx on public.orders(user_id, created_at desc);
create index if not exists favorites_product_id_idx on public.favorites(product_id);
create index if not exists cart_items_user_id_idx on public.cart_items(user_id);
create index if not exists hero_slides_order_idx on public.hero_slides(active, sort_order);
create index if not exists analytics_daily_day_idx on public.analytics_daily(day desc);
create index if not exists products_title_search_idx on public.products using gin (title gin_trgm_ops);
create index if not exists products_description_search_idx on public.products using gin (description gin_trgm_ops);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.favorites enable row level security;
alter table public.cart_items enable row level security;
alter table public.hero_slides enable row level security;
alter table public.analytics_daily enable row level security;

grant select on table public.products to anon, authenticated;
grant select, insert, update, delete on table public.products to service_role;
grant select, insert, update, delete on table public.orders to service_role;
grant select, insert, update, delete on table public.order_items to service_role;
grant select, insert, update, delete on table public.favorites to service_role;
grant select, insert, update, delete on table public.cart_items to service_role;
grant select, insert, update, delete on table public.hero_slides to service_role;
grant select, insert, update, delete on table public.analytics_daily to service_role;
grant usage, select on sequence public.order_items_id_seq to service_role;

create or replace function public.increment_analytics_batch(events jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  event jsonb;
  clean_metric text;
  clean_key text;
  clean_count integer;
begin
  for event in select * from jsonb_array_elements(events)
  loop
    clean_metric := event->>'metric';
    clean_key := left(event->>'key', 180);
    clean_count := least(1000, greatest(1, coalesce((event->>'count')::integer, 1)));
    if clean_metric in ('page_view', 'click') and char_length(clean_key) > 0 then
      insert into public.analytics_daily(day, metric, event_key, event_count)
      values (current_date, clean_metric, clean_key, clean_count)
      on conflict (day, metric, event_key)
      do update set event_count = analytics_daily.event_count + excluded.event_count;
    end if;
  end loop;
end;
$$;

revoke all on function public.increment_analytics_batch(jsonb) from public, anon, authenticated;
grant execute on function public.increment_analytics_batch(jsonb) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('CodartlbShop', 'CodartlbShop', true, 5242880, array['image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- The app uses the service role only in server-side Route Handlers.
-- Public visitors can read product rows and public bucket files, but cannot mutate them directly.
drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
to anon, authenticated
using (true);
