import type { AnalyticsRow } from "@/lib/analytics";

export function AnalyticsDashboard({ rows }: { rows: AnalyticsRow[] }) {
  const views = rows.filter((row) => row.metric === "page_view").reduce((sum, row) => sum + row.event_count, 0);
  const clicks = rows.filter((row) => row.metric === "click").reduce((sum, row) => sum + row.event_count, 0);
  const clickRate = views ? (clicks / views) * 100 : 0;
  const days = Array.from({ length: 14 }, (_, offset) => {
    const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (13 - offset));
    const key = date.toISOString().slice(0, 10);
    return { key, label: new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(date), views: rows.filter((row) => row.day === key && row.metric === "page_view").reduce((sum, row) => sum + row.event_count, 0), clicks: rows.filter((row) => row.day === key && row.metric === "click").reduce((sum, row) => sum + row.event_count, 0) };
  });
  const max = Math.max(1, ...days.flatMap((day) => [day.views, day.clicks]));
  const top = (metric: "page_view" | "click") => [...rows.filter((row) => row.metric === metric).reduce((map, row) => map.set(row.event_key, (map.get(row.event_key) ?? 0) + row.event_count), new Map<string, number>())].sort((a, b) => b[1] - a[1]).slice(0, 7);
  return <main className="admin-workspace"><header className="admin-page-heading"><div><p className="eyebrow">Audience</p><h1>Analytics</h1><p>Lightweight, privacy-friendly totals for storefront views and important clicks.</p></div><span className="admin-heading-count">Last 30 days</span></header><section className="dashboard-metrics sales-metrics"><article><span>Page views</span><strong>{views.toLocaleString()}</strong><small>Across public pages</small></article><article><span>Tracked clicks</span><strong>{clicks.toLocaleString()}</strong><small>Product and conversion actions</small></article><article><span>Clicks per view</span><strong>{clickRate.toFixed(1)}%</strong><small>Engagement indicator</small></article></section><section className="analytics-chart-panel"><div className="panel-heading"><div><p className="eyebrow">Last 14 days</p><h2>Views and clicks</h2></div><div className="chart-legend"><span><i className="views" />Views</span><span><i className="clicks" />Clicks</span></div></div><div className="analytics-bars">{days.map((day) => <div className="analytics-day" key={day.key}><div className="analytics-columns"><i className="views" style={{ height: `${Math.max(day.views ? 4 : 1, day.views / max * 100)}%` }} title={`${day.views} views`} /><i className="clicks" style={{ height: `${Math.max(day.clicks ? 4 : 1, day.clicks / max * 100)}%` }} title={`${day.clicks} clicks`} /></div><span>{day.label}</span></div>)}</div></section><div className="analytics-tables"><section><div className="panel-heading"><div><p className="eyebrow">Content</p><h2>Top pages</h2></div></div>{top("page_view").length ? top("page_view").map(([key, count], index) => <div className="analytics-rank" key={key}><small>{String(index + 1).padStart(2, "0")}</small><strong>{key}</strong><span>{count.toLocaleString()}</span></div>) : <p className="analytics-no-data">No page views recorded yet.</p>}</section><section><div className="panel-heading"><div><p className="eyebrow">Interactions</p><h2>Top clicks</h2></div></div>{top("click").length ? top("click").map(([key, count], index) => <div className="analytics-rank" key={key}><small>{String(index + 1).padStart(2, "0")}</small><strong>{key.replaceAll("_", " ")}</strong><span>{count.toLocaleString()}</span></div>) : <p className="analytics-no-data">No tracked clicks recorded yet.</p>}</section></div></main>;
}
